# Generated by Django 4.1.9 on 2024-04-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("food_cd", models.CharField(max_length=200)),
                (
                    "group_name",
                    models.CharField(choices=[("FOOD", "음식")], max_length=200),
                ),
                ("food_name", models.CharField(max_length=200)),
                ("research_year", models.IntegerField()),
                ("market_name", models.CharField(max_length=200)),
                ("ref_name", models.CharField(max_length=200)),
                ("calorie", models.DecimalField(decimal_places=2, max_digits=7)),
                ("carbohydrate", models.DecimalField(decimal_places=2, max_digits=7)),
                ("protein", models.DecimalField(decimal_places=2, max_digits=7)),
                ("province", models.DecimalField(decimal_places=2, max_digits=7)),
                ("sugars", models.DecimalField(decimal_places=2, max_digits=7)),
                ("salt", models.DecimalField(decimal_places=2, max_digits=7)),
                ("cholesterol", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "saturated_fatty_acids",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                ("trans_fat", models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
