# Generated by Django 4.1.9 on 2024-04-20 05:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_id',
            field=models.CharField(default='asdf', max_length=200),
        ),
        migrations.AlterField(
            model_name='food',
            name='group_name',
            field=models.CharField(choices=[('FOOD', '음식')], default='FOOD', max_length=200),
        ),
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
