# Generated by Django 4.1.9 on 2024-04-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_food_id_alter_food_group_name_alter_food_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='serving_size',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='calorie',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbohydrate',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='cholesterol',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_cd',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='market_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='province',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='ref_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='research_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='salt',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='saturated_fatty_acids',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='sugars',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='trans_fat',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
