# Generated by Django 4.1.9 on 2024-04-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_serving_size_alter_food_calorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='group_name',
            field=models.CharField(choices=[('음식', 'FOOD')], default='FOOD', max_length=200),
        ),
    ]
