# Generated by Django 4.1.9 on 2024-04-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_food_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='group_name',
            field=models.CharField(choices=[('음식', '음')], default='음식', max_length=200),
        ),
    ]
