# Generated by Django 4.1.9 on 2024-04-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_food_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='group_name',
            field=models.CharField(choices=[('Food', '음식')], default='Food', max_length=200),
        ),
    ]
